export const MOCK_MESSAGES = [
  {
    id: 'mock-1',
    userId: 'mock-user-1',
    sender: '영화광',
    message: '와... 이거 진짜 숨 막혔어요ㅋㅋ',
    timeStamp: new Date(Date.now() - 3600000),
    profileColorType: 'PURPLE',
    roomId: 8,
  },
  {
    id: 'mock-2',
    userId: 'mock-user-2',
    sender: '시네마러버',
    message: '저도요ㅠ 남주 표정 너무 찐이었죠.',
    timeStamp: new Date(Date.now() - 1800000),
    profileColorType: 'BLUE',
    roomId: 8,
  },
  {
    id: 'mock-3',
    userId: 'mock-user-3',
    sender: '무비매니아',
    message: '근데 저만 여주 편인가요? 이해되던데요ㅠ',
    timeStamp: new Date(Date.now() - 900000),
    profileColorType: 'RED',
    roomId: 8,
  },
  {
    id: 'mock-4',
    userId: 'mock-user-3',
    sender: '영화광',
    message: '맞아요, 저라도 그랬을 것 같아요.',
    timeStamp: new Date(Date.now() - 900000),
    profileColorType: 'PURPLE',
    roomId: 8,
  },
  {
    id: 'mock-5',
    userId: 'mock-user-3',
    sender: '시네마러버',
    message: '현실 연애 보는 느낌이라 너무 공감됐어요ㅋㅋ',
    timeStamp: new Date(Date.now() - 900000),
    profileColorType: 'BLUE',
    roomId: 8,
  },
  {
    id: 'mock-6',
    userId: 'mock-user-3',
    sender: '무비매니아',
    message: '진짜 감정선 미쳤어요... 보는 내내 몰입했네요.',
    timeStamp: new Date(Date.now() - 900000),
    profileColorType: 'RED',
    roomId: 8,
  },
  {
    id: 'mock-7',
    userId: 'mock-user-3',
    sender: '영화광',
    message: '저 장면 다시 보기 눌렀어요. 너무 찔려서ㅋㅋ',
    timeStamp: new Date(Date.now() - 900000),
    profileColorType: 'PURPLE',
    roomId: 8,
  },
];

export const MOCK_MESSAGES_2 = [
  {
    id: 'mock-1',
    userId: 'mock-user-1',
    sender: '연프러버',
    message: '이번 시즌 보면서 전 남친한테 연락할 뻔했어요ㅋㅋ',
    timeStamp: new Date(Date.now() - 3600000),
    profileColorType: 'PURPLE',
    roomId: 117,
  },
  {
    id: 'mock-2',
    userId: 'mock-user-2',
    sender: '리뷰어',
    message: '헐ㅋㅋ 그건 진짜 제작진 노림수예요. 절대 안 돼요.',
    timeStamp: new Date(Date.now() - 1800000),
    profileColorType: 'BLUE',
    roomId: 117,
  },
  {
    id: 'mock-3',
    userId: 'mock-user-3',
    sender: '매니아매니아',
    message: '근데 진짜 이번엔 감정선 너무 현실적이지 않아요?',
    timeStamp: new Date(Date.now() - 900000),
    profileColorType: 'RED',
    roomId: 117,
  },
  {
    id: 'mock-4',
    userId: 'mock-user-3',
    sender: '연프러버',
    message: '맞아요ㅠ 저 눈물씬 보고 저도 울었어요…',
    timeStamp: new Date(Date.now() - 900000),
    profileColorType: 'PURPLE',
    roomId: 117,
  },
  {
    id: 'mock-5',
    userId: 'mock-user-3',
    sender: '리뷰어',
    message: '와 그 한마디 듣고 완전 무너졌어요ㅠㅠ',
    timeStamp: new Date(Date.now() - 900000),
    profileColorType: 'BLUE',
    roomId: 117,
  },
  {
    id: 'mock-6',
    userId: 'mock-user-3',
    sender: '매니아매니아',
    message: '진짜요ㅋㅋ 감정 회복할 새도 없이 몰입했어요.',
    timeStamp: new Date(Date.now() - 900000),
    profileColorType: 'RED',
    roomId: 117,
  },
  {
    id: 'mock-7',
    userId: 'mock-user-3',
    sender: '연프러버',
    message: '끝나고 나서 멍했어요. 너무 내 얘기 같아서요.',
    timeStamp: new Date(Date.now() - 900000),
    profileColorType: 'PURPLE',
    roomId: 117,
  },
];

export const MOCK_MESSAGES_3 = [
  {
    id: 'mock-1',
    userId: 'mock-user-1',
    sender: '드라마만봐',
    message: '이거 보면서 괜히 울컥했어요ㅠ',
    timeStamp: new Date(Date.now() - 3600000),
    profileColorType: 'PURPLE',
    roomId: 112,
  },
  {
    id: 'mock-2',
    userId: 'mock-user-2',
    sender: '이시라님',
    message: '저도요… 요즘 제 얘기 같아서 더 와닿았어요.',
    timeStamp: new Date(Date.now() - 1800000),
    profileColorType: 'BLUE',
    roomId: 112,
  },
  {
    id: 'mock-3',
    userId: 'mock-user-3',
    sender: '한드최고',
    message: '대사 하나하나가 다 위로되더라고요.',
    timeStamp: new Date(Date.now() - 900000),
    profileColorType: 'RED',
    roomId: 112,
  },
  {
    id: 'mock-3',
    userId: 'mock-user-3',
    sender: '드라마만봐',
    message: '맞아요. 그냥 ‘괜찮다’는 말 듣는 기분이었어요.',
    timeStamp: new Date(Date.now() - 900000),
    profileColorType: 'PURPLE',
    roomId: 112,
  },
  {
    id: 'mock-3',
    userId: 'mock-user-3',
    sender: '이시라님',
    message: 'OST도 너무 좋아서 바로 저장했어요ㅋㅋ',
    timeStamp: new Date(Date.now() - 900000),
    profileColorType: 'BLUE',
    roomId: 112,
  },
  {
    id: 'mock-3',
    userId: 'mock-user-3',
    sender: '매니아매니아',
    message: '그 장면에서 그 노래 나올 때 진짜 완벽했죠ㅠ',
    timeStamp: new Date(Date.now() - 900000),
    profileColorType: 'RED',
    roomId: 112,
  },
  {
    id: 'mock-3',
    userId: 'mock-user-3',
    sender: '드라마만봐',
    message: '여운이 오래가요... 끝나고 한참 멍했어요.',
    timeStamp: new Date(Date.now() - 900000),
    profileColorType: 'PURPLE',
    roomId: 112,
  },
];

export const MOCK_MESSAGES_4 = [
  {
    id: 'mock-1',
    userId: 'mock-user-1',
    sender: '영화광',
    message: '와… 첫 장면부터 분위기 미쳤다. 70년대 감성 그대로 살린 거 인정.',
    timeStamp: new Date(Date.now() - 3600000),
    profileColorType: 'PURPLE',
    roomId: 128,
  },
  {
    id: 'mock-2',
    userId: 'mock-user-2',
    sender: '시네마러버',
    message: '납치인데 왜 이렇게 웃기냐고요ㅋㅋ 긴장감이랑 블랙코미디 밸런스 완전 찰떡.',
    timeStamp: new Date(Date.now() - 1800000),
    profileColorType: 'BLUE',
    roomId: 128,
  },
  {
    id: 'mock-3',
    userId: 'mock-user-3',
    sender: '무비매니아',
    message: '맞아요ㅋㅋ 기자들 대응하는 장면들 현실풍자 너무 세서 순간 정색함.',
    timeStamp: new Date(Date.now() - 900000),
    profileColorType: 'RED',
    roomId: 128,
  },
  {
    id: 'mock-4',
    userId: 'mock-user-4',
    sender: '영화광',
    message: '근데 납치범 캐릭터… 왜인지 계속 불쌍했음ㅠ 사연 너무 현실적.',
    timeStamp: new Date(Date.now() - 880000),
    profileColorType: 'PURPLE',
    roomId: 128,
  },
  {
    id: 'mock-5',
    userId: 'mock-user-5',
    sender: '시네마러버',
    message: '그니까요. 웃기다가도 갑자기 먹먹해지는 그 느낌;; 변성현 감독 스타일 그대로.',
    timeStamp: new Date(Date.now() - 860000),
    profileColorType: 'BLUE',
    roomId: 128,
  },
  {
    id: 'mock-6',
    userId: 'mock-user-6',
    sender: '무비매니아',
    message: '특히 착륙 직전 긴장감… 브금이랑 연출 같이 터져서 소름 돋았음.',
    timeStamp: new Date(Date.now() - 830000),
    profileColorType: 'RED',
    roomId: 128,
  },
  {
    id: 'mock-7',
    userId: 'mock-user-1',
    sender: '영화광',
    message: '마지막 엔딩 멘트… 와… 제목이 왜 굿뉴스인지 단번에 이해됨ㅠㅠ',
    timeStamp: new Date(Date.now() - 800000),
    profileColorType: 'PURPLE',
    roomId: 128,
  },
];